version: '3.8'
services:
  postgres:
    image: postgres:13.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
